### PR TITLE
chore: disable multiword-rule

### LINKED ISSUE #192: 🐛 eslint vue/multi-word-component-names naming limitation for routes
### Versions

- nuxt: v2.15.8
- node: v14.15.1

### Reproduction

I tried to add a codesandbox link but this is an error during build that would not show on console

### Steps to reproduce

1.  Create nuxt app
2.  Create a single word component, either in `/layouts`, `/components` or `/pages`
3.  Check build error, it says  `error  Component name "name" should always be multi-word`

### What is Expected?

For example if I create `pages/home.vue` or `pages/home/index.vue` then I should be able to go to  `http://localhost:3000/home` according to the [docs ](https://nuxtjs.org/docs/features/file-system-routing/)

Also according to [docs](https://nuxtjs.org/docs/directory-structure/layouts#layouts-directory) I should be able to create `layouts/default.vue`

### What is actually happening?

During build it shows the error I mentioned before

If I rename my component to VHome.vue then it works but it's not ideal since that changes my route too

### Current workaround
I changed my Nuxt version to v2.15.7 and it worked, it built and the routes were how I wanted. However if I upgrade to the latest version of Nuxt, I can go to `.eslintrc.js` and set:
```javascript
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
  },
  parserOptions: {
    parser: '@babel/eslint-parser',
    requireConfigFile: false,
  },
  extends: ['@nuxtjs', 'plugin:nuxt/recommended', 'prettier'],
  plugins: [],
  // 🚨 IMPORTANT: this is the config that fixes it at the moment
  rules: {
    "vue/multi-word-component-names": ["error", {
      "ignores": ["default", "home"]
    }]
  },
}
```

However this is not convenient because I have to put the name of every single file in the array

💖 Thank you for taking the time to review this, lmk if I can provide more information

### PR DESCRIPTION
**Pull request by manniL**
Not ideal for page components :( 

Resolves #192 
Better would be disabling it for the pages folder only I'd say 😋

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
Could we implement via overrides instead (e.g. for `**/pages/**`), as you've linked [to this](https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns)?

**Review by iamarpitpatidar — CHANGES_REQUESTED** [review]
dude, why not just enable it for components. there you go.. as @danielroe said.
```
  rules: {
    'vue/multi-word-component-names': 'off',
  },
  overrides: [
    {
      files: ['components/**'],
      rules: {
        'vue/multi-word-component-names': 'error',
      }
    }
  ]
```

**Comment by manniL** [comment]
> yeah, I think is better than just disabling it. as @danielroe said.
> 
> ```
>   rules: {
>     'vue/multi-word-component-names': 'off',
>   },
>   overrides: [
>     {
>       files: ['components/*.{js,ts,vue}'],
>       rules: {
>         'vue/multi-word-component-names': 'error',
>       }
>     }
>   ]
> ```

I'd probably do it the other way around, given that components could live in many folders but page components usually only in `pages`.

**Review by iamarpitpatidar — APPROVED** [review]
okay yeah that's smart..

**Comment by iamarpitpatidar** [comment]
@manniL can you check why test is failing tho ?

**Review by danielroe — APPROVED** [review]

**Review by clarkdo — APPROVED** [review]

**Comment by KareemDa** [comment]
when this feature will be released?

installing latest version: `8.0.0`  is still giving the same error

**Comment by rchl** [comment]
It doesn't handle the case when page components are in `test/fixture/...` for example.
Also why does it apply to `.js` and `.ts` extensions? I would think that it should only apply to `.vue`?

**Comment by pi0** [comment]
@rchl I suppose `.js` would be mostly useful for components with render function with `// @vue/component` however didn't try. It also makes sense to ignore `**/pages/`, project in subdir.

**Comment by 0x3333** [comment]
In my case, I use an 'src' folder for all my components, assets, pages, etc. The lint kicks-in in this case.

**Pull request merged**
