### PR TITLE
feat: sort-package-json

### PR DESCRIPTION
**Pull request by antfu**
This PR adds the ablity to sort package.json on linting. Supporting best practices, for examples in `exports` the `types` should comes first, etc.

### CODE REVIEW

**Comment by pi0** [comment]
Nice idea! Only thing can you please check if current rules are consistent with [sort-package-json](https://github.com/keithamus/sort-package-json/blob/master/index.js) i used this convention on current packages

**Comment by pi0** [comment]
Also maybe we should introduce it for tooling/internal preset? 

The promise of main `@nuxt/eslint-config` is to be non opinionated about code style and focus on code lint rules
> Non-opinionated [ESlint](https://eslint.org/) configuration for Nuxt 3 apps.

**Comment by antfu** [comment]
Yes, I was talking to Denial, we should have an eslint config for toolings and have this there.

**Comment by Atinux** [comment]
What would be the name of that package then?

I kind of like the fact it can be opinionated somehow (like Nuxt)

**Comment by antfu** [comment]
We were thinking `@nuxt/eslint-config-internal` or `@nuxt/eslint-config-toolings` from our last discussion I think

**Pull request closed without merging**
