### PR TITLE
fix(vue): disable `vue/no-v-model-argument` for Vue 3

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Review by Atinux — APPROVED** [review]

**Comment by pi0** [comment]
Can you please explain why disabling this rule? (https://eslint.vuejs.org/rules/no-v-model-argument.html)

**Comment by danielroe** [comment]
I think the root issue here is that we are still exporting Vue 2 eslint rules. Should we update to Vue 3?

https://github.com/nuxt/eslint-config/issues/216

**Comment by pi0** [comment]
Let's fix #216 then for proper Vue 3 detection. We could detect installed vue version to adjust preset behavior (https://github.com/nuxt/eslint-config/pull/217#issuecomment-1161473288)

**Comment by danielroe** [comment]
Nice idea 👍

**Pull request closed without merging**
